# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macos-latest'
  
trigger:
- Dev
# The `certSecureFile` and `provProfileSecureFile` files are uploaded to the Azure Pipelines secure files library where they are encrypted.
# The `P12Password` variable is set in the Azure Pipelines pipeline editor and marked 'secret' to be encrypted.
steps:
- task: Xcode@5
  displayName: 'Build xcode project'
  inputs:
    actions: 'build'
    scheme: 'LocationTest'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 9, 10, 11, default, specifyPath
    #teamId: UBLBCH5PYQ
    #exportTeamId: UBLBCH5PYQ
    signingOption: 'manual'
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
    packageApp: true

- task: SlackNotification@5
  displayName: 'Post Slack Notification'
  inputs:
    SlackApiToken: '$(SlackToken)'
    Channel: '#ios_pipeline'
    Message: 'Hi, you''re project is builded'
    Title: 'Build-Slack job terminated'
    Color: '#439FE0'